### PR TITLE
Removing unnecessary dependencies

### PR DESCRIPTION
**Pull request by lukas-krecan-lt**

### CODE REVIEW

**Comment by io-german** [comment]
Hey, thanks for the PR. 
I'll check how the package works with your changes in a few days.

**Comment by aurambaj** [comment]
would be great to have that, I'm having build issue because of `synchronize` bringing an old version of `fibers` (@1.0.15)

**Comment by lukas-krecan-lt** [comment]
We are using it as Git dependency and it works fine. So until it's released, you can use this in `package.json`

```
"java-properties-flat-loader": "github:adleritech/java-properties-flat-loader#588eeb2"
```

**Comment by aurambaj** [comment]
thanks for the suggestion @lukas-krecan-lt. I ended up replacing it with a "local" loader for now since it is not too complicated.

**Review by io-german — APPROVED** [review]

**Comment by io-german** [comment]
Thanks again for the PR and sorry for such a late response. Tests passed, and I also made a manual sanity test. I'll publish an update to NPM ASAP.

Don't remember why this `synchronize` call is here in the first place. Probably an artifact from the time I replaced a simple file parsing routine with `properties` module, but scanning through the commit history, I have found no justification for it.

**Comment by io-german** [comment]
@lukas-krecan-lt the package is updated and published to NPM.

**Comment by lukas-krecan-lt** [comment]
Thanks

**Pull request merged**
